twig:
  default_path: "%kernel.project_dir%/templates"
  file_name_pattern: ["*.twig"]
  form_themes: ["bootstrap_5_layout.html.twig"]

  # globals
  globals:
    HOME_PAGE: "home"
    CART_PAGE: "cart"
    ORDER_PAGE: "order"
    CATEGORY_PAGE: "category"
    PRODUCT_PAGE: "product"
    ORDER_CONFIRMATION: "orderConfirmation"
    SIGN_UP: "signup"
    SIGN_IN: "signin"

    PRODUCT_CAT_IMG_FOLDER: "assets/img/products/categories/img/"
    PRODUCT_IMG_FOLDER: "assets/img/products/img/"

when@test:
  twig:
    strict_variables: true
