controllers:
  resource: ../src/Controller/
  type: attribute

#---------- Configuration des routes de l'app ------------
#
# --------------------------------------------------------
#           Route classique
# --------------------------------------------------------
# [nom_de_la_route]
# app_article:
#     [route]
#     path:  /blog/{catId}/{articleId}
#
#     [namespace\nomController::nomMethodeConcernée]
#     controller: App\Controller\ArticleController::index
#
#     [methodes HTTP authorisées]
#     methods: GET|HEAD
#
#     [les valeurs par défaut des paramètre d'url]
#     defaults:
#         pageId: 1
#         articleId: null
#
#     [obligations sur les paramètres d'url]
#     requirements:
#         pageId: \d+
#         articleId: \d+
#
#     [conditions d'activation de la route]
#     syntaxe pour les conditions: https://symfony.com/doc/2.8/components/expression_language/syntax.html
#     condition: "request.headers.get('User-Agent') matches '/firefox/i'"
#
#
#
# --------------------------------------------------------
#           Route vers un sous-domaine
# --------------------------------------------------------
# [nom_de_la_route]
# mobile_article:
#     [route]
#     path:  /blog/{catId}/{articleId}
#
#     [Hôte]
#     host: "{sousDomaine}.nom-de-domaine.com"
#
#     [namespace\nomController::nomMethodeConcernée]
#     controller: App\Controller\ArticleController::mobileArticle
#
#     [methodes HTTP authorisées]
#     methods: GET|HEAD
#
#     [les valeur par défaut des paramètre d'url]
#     defaults:
#         pageId: 1
#         articleId: null
#         sousDomaine: m
#
#     [obligations sur les paramètres d'url]
#     requirements:
#         pageId: \d+
#         articleId: \d+
#         sousDomaine: m|mobile
#
#     [conditions d'activation de la route]
#     syntaxe pour les conditions: https://symfony.com/doc/2.8/components/expression_language/syntax.html
#     condition: "request.headers.get('User-Agent') matches '/firefox/i'"

# Front Office
app_home: # Page Accueil
  path: /
  controller: App\Controller\HomeController::index

app_category: # Page toutes les catégories
  path: /categories/{cat}/{gender}
  controller: App\Controller\CategorieController::index
  methods: GET
  defaults:
    cat: null
    gender: null

app_product:
  path: /product/{cat}/{id}
  controller: App\Controller\ProductController::index
  methods: GET
  defaults:
    cat: null
    id: null
  requirements:
    id: '\d+'

app_add_to_cart:
  path: /cart
  controller: App\Controller\CartController::index
  methods: POST

app_cart:
  path: /cart/details
  controller: App\Controller\CartController::cartDetails

app_order:
  path: /order/step/{step}
  controller: App\Controller\OrderController::index

# Back Office Admin
app_admin:
  path: /admin
  controller: App\Controller\AdminController::dashboard

app_admin_member_management:
  path: /admin/members
  controller: App\Controller\AdminController::memberManagement

# Back Office Member
app_member:
  path: member/profile
  controller: App\Controller\MemberController::dashboard

# Login / Logout
app_login:
  path: /login
  controller: App\Controller\SecurityController::login
  methods: [GET, POST]

app_logout:
  path: /logout
  methods: GET

# Inscription
app_register:
  path: /register
  controller: App\Controller\RegistrationController::register

app_verify_email:
  path: /verify/email
  controller: App\Controller\RegistrationController::verifyUserEmail

app_email_conf_sent:
  path: /signup/confirmation
  controller: App\Controller\RegistrationController::postSignUp

# Stripe
app_stripe:
  path: /stripe
  controller: App\Controller\StripeController::index

app_stripe_charge:
  path: /stripe/create-charge
  controller: App\Controller\StripeController::createCharge
  methods: POST

app_stripe_success:
  path: /order/confirmation/stripe
  controller: App\Controller\StripeController::orderConfirmation

app_stripe_fail:
  path: /payment/failure/stripe
  controller: App\Controller\StripeController::paymentFailure

# Paypal
app_paypal:
  path: /paypal
  controller: App\Controller\PaypalController::index

app_paypal_success:
  path: /order/confirmation/paypal
  controller: App\Controller\PaypalController::orderConfirmation

app_paypal_fail:
  path: /payment/failure/{err}
  controller: App\Controller\PaypalController::paymentFailure
  methods: GET
  defaults:
    err: null
